config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :articles
  get 'signup', to:'users#new'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy
  validates :username, presence: true,
    length: {minimum: 3, maximum: 25},
    uniqueness: { case_sensitive: false }
  validates :email, presence: true,
    length: {maximum: 105},
    uniqueness: { case_sensitive: false },
    format: { with: URI::MailTo::EMAIL_REGEXP}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perfom that action'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show

  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully!"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully!"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to article_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was succesfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category name updated succesfully'
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your login details'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:index, :show, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed in"
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was succesfully updated"
      redirect_to @user
    else
        render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil unless current_user.admin?
    flash[:notice] = "Account and all associated articles succesfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    # compile URL which can be used in <img src="RIGHT_HERE"...
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

    image_tag(gravatar_url,alt: user.username)
  end
end

app/views/articles/_article.html.erb
<%= link_to 'Create article', new_article_path %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Autor </th>
      <th>Categories</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td>
          <% if article.user %>
            <%= link_to article.user.username, user_path(article.user) %>
          <% end %>
        </td>
        <td>
        <% if article.categories.any? %>
          <%= render article.categories %>
        <% end %>
        </td>
        <td>
            <%= link_to 'Show', article_path(article) %>
            <% if logged_in? && (article.user == current_user || current_user.admin? ) %>
              <%= link_to 'Edit', edit_article_path(article) %>
              <%= link_to 'Delete', article_path(article), data: { "turbo-method": :delete, turbo_confirm: "are you sure?" } %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article,  data: {turbo: false}) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
    <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.collection_select :category_ids, Category.all, :id, :name, { prompt: 'Make your selection from the list below (can be empty)'}, { multiple: true, size: 3} %>
    </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1> Edit article </h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles list', article_path %> 

app/views/articles/index.html.erb
<h1>Articles listing pages:</h1>
<p><%= link_to 'Create new article', new_article_path %></p>

<%= will_paginate @article %>
<%= render 'article' %>

app/views/articles/new.html.erb
<h1> Create a new article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>showing articles details</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>By: </strong><%= @article.user.username %></p>
<p>
  <% if @article.categories.any? %>
    <%= render @article.categories %>
  <% end%>
</p>

<% if logged_in? && (@article.user == current_user || current_user.admin? ) %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete, turbo_confirm: "are you sure?" } %>
<% end %>
<%= link_to 'Return to articles list', articles_path %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category)%> 

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category,  data: {turbo: false}) do |f| %>
  <p>
    <%= f.label :name, 'Category name' %><br/>
    <%= f.text_field :name, placeholder: 'Enter a name' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1> Edit a new category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories:</h1>
<%= will_paginate @categories %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Articles</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= pluralize category.articles.count, "article" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1> Create a new category</h1>
<%= render 'shared/errors', obj: @category %>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Category <%= @category.name %></h1>
<br>
<% if logged_in? && current_user.admin? %>
  <%= link_to 'Edit category name', edit_category_path(@category) %>
<% end %>

<h3>Articles </h3>
<%= will_paginate @articles %>
<%= render 'articles/article' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= name %>:
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li>
      <%= link_to "Alpha Blog", root_path %>
    </li>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "Articles", articles_path %>
      <% if logged_in? %>
      <ul>
        <li>
          <%= link_to "View articles", articles_path %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to "Create an article", new_article_path %>
          </li>
        <% end %>
      </ul>
      <% end %>
    </li>
    <li>
      <%= link_to "Categories", categories_path %>
      <% if logged_in? %>
      <ul>
        <li>
          <%= link_to "View categories", categories_path %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to "Create a category", new_category_path %>
          </li>
        <% end %>
      </ul>
      <% end %>
    </li>
    <li>
      <%= link_to "Bloggers", users_path %>
    </li>
    <li>
      <% if logged_in? %>
      <%= "(Admin)"if current_user.admin?  %>
      <%= link_to current_user.username, user_path(current_user)  %>
      <ul>
        <li>
          <%= link_to "Edit your profile", edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Delete profile", user_path(current_user), data: { "turbo-method": :delete, turbo_confirm: "are you sure?" } %>
        </li>
      </ul>
      <%= link_to "Logout", logout_path, data: { "turbo-method": :delete }  %>
      <% else %>
        <%= link_to "Log in", login_path %>
        <%= link_to "Sign up", signup_path %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
<h1>Alpha Blog</h1>
<p> This is a simple blog made with vanilla Ruby on Rails code</p>
<%= link_to "Sign up!", signup_path %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2> The following erros prevented the <%= obj.class.name.downcase %> from being saved</h2>
  <% obj.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user,  data: {turbo: false}) do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email, placeholder: 'enter your email address' %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password, placeholder: 'choose password' %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account" )  %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1> Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1> Alpha Bloggers</h1>

<%= will_paginate @user %>
<table>
  <thead>
    <tr>
      <th></th>
      <th>User</th>
      <th>Email</th>
      <th>Articles</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= gravatar_for(user, size: 50) %>
        </td>
        <td><%= user.username %> </td>
        <td><%= user.email %></td>
        <td><%= pluralize user.articles.count, "article" %></td>
        <td>
            <%= link_to 'Show', user_path(user) %>
            <% if logged_in? && (user == current_user || current_user.admin? ) %>
              <%= link_to 'Edit', edit_user_path(user) %>
            <% end %>
        </td>
        <td>
          <% if current_user&.admin? %>
            <%= link_to "Delete user", user_path(user),  data: { "turbo-method": :delete, turbo_confirm: "are you sure?" } %>
          <%end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1> Sign up for Alpha blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size:200 %>
<br>
<% if logged_in? && (@user == current_user || current_user.admin? ) %>
  <%= link_to 'Edit your profile', edit_user_path(@user) %>
<% end %>

<h3>Articles </h3>
<%= will_paginate @articles %>
<%= render 'articles/article' %>